### PR TITLE
Looking into adding additional providers

### PR DESCRIPTION
**Pull request by Ghosts**
Exploring types & methods for additional providers with options from firebase per #10

### CODE REVIEW

**Comment by Ghosts** [comment]
This is *not* merge-ready, just wanted to open for discussion. Is this sort of what you were thinking of detailed in #10 ?

Also was wondering - how are you testing locally? I wasn't quite sure how to import the hooks into a test project when it's not published, have not tested any of the above due to that, but I wanted to see if that matches the approach you were thinking as well.

**Comment by aleksanderbrymora** [comment]
Hi and thanks for the interest!
Re #10: there are a few methods to sign in with popup in firebase, and currently we have 2 of them working (google, and facebook). There is one general hook that just receives an auth provider and does the work.

Re testing: sadly i dont have any internal testing, as this is my first package that im, quite frankly, learning on. But to test it locally in a react project i use `yarn link` functionality that links the project to your global repo of packages. Details on how I do that are in a #6 merged pull request.

I will update the readmes as soon as i can to let people know of the bigger picture and how to actually use things.
But for your testing you should be able to use `useAuth('name of the provider')` which then returns the usuall structure for that hook - `[loading, error, data]` - where data is an object with an `onClick` event that needs to be spread to the button to add functionality to it. Names of the providers that I'm aiming to support are specified in `useAuth` in `AuthType` type

**Comment by Ghosts** [comment]
Sweet! I'll take a look at #6  and see if I can get that running locally. Above changes should conform to the current structure you had with `useAuth('name')`, I also added optional parameters for the `addScope` & `setCustomParameters` that you are able to pass into firebase auth providers. 

Once I get a local example working for testing I'll see if the ones I added work as expected. I believe that they all have the `signInWithPopUp()` functionality supported but firebase documentation has been a bit iffy in my experience.

**Comment by aleksanderbrymora** [comment]
> firebase documentation has been a bit iffy in my experience
This is why im actually doing this project... As i introed in the readme it's surprisingly easy but still somehow hard to get into.

Havent thought of any other parameters to be passed in to `useAuth`, so I'd be keen to have a look at your idea

**Comment by Ghosts** [comment]
@aleksanderbrymora 

Just got the `yarn link` functionality working. Created a little test page locally for `useAuth`. Confirmed that Twitter, Apple, Google, Facebook, Microsoft, and GitHub were creating pop-ups to their respective sites.

Just included apple & microsoft in this PR.

**Comment by Ghosts** [comment]
Sure thing :) currently using firebase in a prod re-write and was considering making hooks for auth, calls, etc. This seemed like a great opportunity to jump in and help, will watch the repo and take a look at any issues you have marked for help-wanted, etc. If you want more help overall feel free to reach out.

**Pull request merged**
